apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kustomization-staging.yaml
  - kustomization-prod.yaml
  - image-repository.yaml
  - image-policy-staging.yaml
  - image-update-automation-staging.yaml
