apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sillytavern-data
  labels:
    app.kubernetes.io/name: sillytavern
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-k8s-volumes
  resources:
    requests:
      storage: 5Gi
