apiVersion: v1
kind: Service
metadata:
  name: sillytavern
  labels:
    app.kubernetes.io/name: sillytavern
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sillytavern
  ports:
    - name: http
      port: 8000
      targetPort: 8000
