cloudflare:
    api_token: ENC[AES256_GCM,data:Rjr8WsFZq+956aUWFoB5HjK9kngphW7+Hj+uFpNVgArb36vQKKAN0fub3eK5BvZnJucULug=,iv:6KPYYt0N00o45+A4IKLBSdPkAOjuBmks/qDc5UYXMAo=,tag:yiylq2QAlRhzBZnftFm5mQ==,type:str]
adguard:
    username: ENC[AES256_GCM,data:tfCPqNQ=,iv:SCS+mOzqtxXSkFv9e4xJn603sy8byzZaEqICXz5srKo=,tag:0P/dCkDjtVgyu5vN0osk1w==,type:str]
    password_hash: ENC[AES256_GCM,data:udyNSF5qqBawa8eOlIHLpTLxy+LiAY5bF+Hnei2LWDZWRigipKcQNx483p2adWzryY2A9jWmFfmNr8HH,iv:q0l89vUTViIejJXGJlEg0YsOl4A5nCVip8SNKPAzzfc=,tag:4WmA0tCA+6VH4/etsXb50g==,type:str]
gatus:
    discord_webhook_url: ENC[AES256_GCM,data:UKJ/KQWeZgBl54FwsmrT9aa3x3us3Fs6UgOKUwmJ0iCLq5urYz2/YHK8eiBtUtPXxd5GLrheJXmPXdps2L/C73Glfn1wfAw3HeUwNwZp06+VQEwKyLLsO38d/Jh9cPkxBlEPzsxG+tJU+tBAJaN1y4Cf87mfSSGtkg==,iv:8M7E706/yorp06T+378hn5u7BousGZmbRRXmRn9fDcQ=,tag:jNbvoCJ+sgqvW1DlGuRqkw==,type:str]
    basic_auth_hash: ENC[AES256_GCM,data:R+lcD2Zf0s97+bp2lXTNbRSQnBEQQbialtow5Xr40cyrAz2rSHkKTJBQPMj4ccbCIRd6MtZbaRwPNuwf,iv:9tSAtjSdOam14LOKfRzP+1PWInEoTFwd3PqTm7Nkpn8=,tag:jBcxpMV4HNmh/D702t9vVw==,type:str]
samba:
    koji-genba-password: ENC[AES256_GCM,data:XymdMrWNZe9SeUY1lA==,iv:G9bPtDOSxG1nfl9i9dmoKUHYq7wQoys64MBO0FrDpFU=,tag:YPOrgscQhOqxvLWT///TCg==,type:str]
sillytavern:
    username: ENC[AES256_GCM,data:62SY9elCywjE,iv:kpecRWrKMPSFRjp/iWyFTZ3rnRqC7zULKil4qECJ7DQ=,tag:LlLOO39JxPWoCtFupcCrSg==,type:str]
    password: ENC[AES256_GCM,data:VqV/iEAfF5eQVenA+Q==,iv:d4WE1cEatdH9x6TqKjZYCDluiKuqWAMKZqsAJH+so5Y=,tag:rbHOizgeynRyLSSGoMrV6w==,type:str]
healthchecks:
    ping_url: ENC[AES256_GCM,data:+N4BhqDYrLeuuHSuQwJKDJ+WPm7vl1KMuk1OBRfs/hdbvaEGZyGZzCIUTsMV6BMw5TnD/lbTAQI=,iv:jaGyacuXNAxtwAQ8tHGXZEbKZCb+JwRFns2pHjpdASs=,tag:heh/6B3APVKKOpOvVdC5tA==,type:str]
sops:
    age:
        - recipient: age1a8v97ung7t9g39vdxsdxgzta4fq4hz7hv7yezzlx6ac7xfgqgsws420x6u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGb1JncjJzZTdHaTJyODVp
            bjNKZ2I5cUpnb0FHRnBWN0xNa0RxVGZQandRCm9NUEZ5eVpGWG03U20vN0xkeGhn
            MStNKzBNZTA0L3JEdS9wM1VkUjF0alUKLS0tIHVHMC9MR2grVmc3L2d0elBxNFpq
            QzlnbHpPdytnandTWmhtbnl3R0lkcncKDVq3iv9NSvX12dTBg2tmbfR9vmpOG6AQ
            RywAM8IfXFoWN8Cns+yBxUAIz62URflctfOwlK6KTJoB4PMBpXkYtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-05T05:09:53Z"
    mac: ENC[AES256_GCM,data:NdwccEDGJQn1RRkhIpBj2bWDbIFuxcpGy7nhgDEK1UYSMe2UpyGNjaeQzt46HQI3cZUotJBp2Bfs0RZAadixOYcDYrwUOeJkDJ8SJKUVhj5AOtU4ilNgQ4WHclfLiOhsnC/HdP4R9gHVpW1S3EHy4X0Hv+V5QcyJpD6mVhTt1sw=,iv:PdueVGbsVIN6pQGTfbSrMH+5ydMI9XTpvAghcMBn5ZE=,tag:4FuuP18JmTYUs4ljH1wHOQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
