cloudflare:
    api_token: ENC[AES256_GCM,data:Ab6guD/NeGPx26eVtACqxNtHoR+Vxeuyac9p3sTjvLX/IeaNplEISp6lDnNAFhMIA5kXmps=,iv:lWL4TZZoMl1iRmaRL6Z6ixUGdw82/vF+mdCXD7InIZc=,tag:LNc+B0fqa9ylqaSobkAnbg==,type:str]
adguard:
    username: ENC[AES256_GCM,data:J9sDxRc=,iv:RLv/S3IKBYxKqv21p2RSFI0e2wKc0LIQDSCY0EpCpDA=,tag:UfTm/ovEFQHB3ecL+dPSyw==,type:str]
    password_hash: ENC[AES256_GCM,data:njIGcJnImMNgDXsKPPYKEad3lbCSHf7c3TAYHzCXdGuvmfmlPxTZyW095myA6QDGjrJ+0P17lLNfqjKJ,iv:9r18V1WPk6V/lZX6fsOaPEaflmdvPxUgRiSFczfYvrE=,tag:xZrQxMDLmZScZ/N5Xot78w==,type:str]
gatus:
    discord_webhook_url: ENC[AES256_GCM,data:1fjbxNN4RpX2tCYSbvZovjVs+jOfPtVSlYgy/0IR8yL3bzVdBcqqoZIJouZgPeAjctVTSa11GZi7n0khe+PMc7sYZqN4K7PL1gWSPS2bJ3Y42mcSYv4NlCGwGIS681vxHzowuP+HMT5M0ye9b9QJ0fBx/Z0MobpUAw==,iv:Rvrgd6LP5Sj/rq0HaS1CiyOCy0Z+yS4MKo+L3A7YjKM=,tag:aL5NGCzlqWPe9uoZSDa2ZQ==,type:str]
    basic_auth_hash: ENC[AES256_GCM,data:KuNCy4YZBfLu0eObCHpsbJkq+k9mBrAOxgaO/UnHMLsTzL5kVWfNHzKduxvGL1x5mGWB/XZAwE9raZNT,iv:CO/sWbXEcsTB0L296t8nFNTUiDI+RXWqoWDFvovp3p4=,tag:87y3xL0vZLDvnSUoO4ZEzA==,type:str]
samba:
    koji-genba-password: ENC[AES256_GCM,data:DAtMKWEpkpmhIP03sA==,iv:PYhsJLD+yzfkDl7T2KUziyPspTs7pAYSjqCxFKBrGIA=,tag:kzMzCKkpP/8fWBLCtrZnMg==,type:str]
sillytavern:
    username: ENC[AES256_GCM,data:ZgUL/CISM7Nm,iv:liE0A75mWexl0HGivyvCQAZqNRuwzx7aR9eqbsQ0ZkY=,tag:K1vUKVVHFp1JKFs7un0RFQ==,type:str]
    password: ENC[AES256_GCM,data:hNCERsNIJlxifF7dUg==,iv:vefpfPLZHFmDB5iMw/uuSulZsmuEfBVr6lxwR0Zmy5M=,tag:TPs5cpKOvd6HG5h8apINrg==,type:str]
healthchecks:
    ping_url: ENC[AES256_GCM,data:19FUNIw22K1rwoDXitEPhNZQCXRFWqyqYChp0LGNt79yiWaGbAXqq6oLAsQzirVfzzO7WUJCqBI=,iv:uoWtCO+4fOZDj0xi/wXl0afJA7W76saDgEj8PlUYRCQ=,tag:JQkvk1mLz73XYM303c1zXQ==,type:str]
sops:
    age:
        - recipient: age1a8v97ung7t9g39vdxsdxgzta4fq4hz7hv7yezzlx6ac7xfgqgsws420x6u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMXRNbVlqL1lzY0FBN3BG
            TkxsYUxBWVkwZkJ0K3lXVVdOWm5zOVo1WGtBCjY4cW5TNjY1dUluM0RrSi9YcnlY
            aVBwdUR2ZDJydXVRaXd1T2N3NGRYbUUKLS0tIGwxWmFoSG5rbHdXYko1OWNHSnU5
            ZjYvNW9vTlhsaG5nU0I5K2MrbGtWRDAK4Ql3EttWhNT6dhlOrgFczdSAuCPKuIdu
            qrKTuDV2pz2uolW2kqLB27PRN8fCeKaAGZ/K7BpKwnU3u6Prys7Wtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-23T14:56:23Z"
    mac: ENC[AES256_GCM,data:DsJsDYNTS83dRaql+mgvWPR8XfPjXjaVFxUo8SywbnH5JPiu08pOtObo2ERdY6QkMh+ODi0F8ExouZ6Hb4wpEHmNEazEhJQuJLy7pLPJcKkFzB9hCVTS3tP8NjSZJV7BosrBNFp/XJdNTQyL0jrvUuXSqjU67AfaodvqpfmZcQY=,iv:5unPJMgzpNnUQj9hVs+tddSpe4OdOdv3edXYpEkJDSU=,tag:iTLQF/27MlcL8J73FtVgPw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
