apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: samba-shared-hdd-storage
  namespace: samba
  labels:
    app.kubernetes.io/name: samba
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-shared-hdd-static
  volumeName: samba-shared-hdd-pv
  resources:
    requests:
      storage: 18Ti
